module.exports = {
	content: ['./src/**/*.{js,jsx,ts,tsx}'],
	plugins: [],
	theme: {
		extend: {
			borderWidth: {
				'0': '0',
				'1': '1px',
				'2': '2px',
				'3': '3px',
				'4': '4px',
				'6': '6px',
				'8': '8px',
				DEFAULT: '1px',
			},
			colors: {
				black: '#000000',
				blue: '#368ef8',
				blueBg: '#2BD3F8',
				blueStatus: '#2BD3F8',
				darkBlue: '#172B85',
				darkGrey: '#4D4D4D',
				green: '#78d359',
				greenInput: '#5DCB42',
				grey: '#C4C4C4',
				// greyBg: '#E5E5E5',
				// greyBg: '#FFFFFF',
				greyBg: '#FAFAFA',
				greyThird: '#F2EDED',
				lightGrey: '#F3F3F3',
				linkStatus: '#6E82AB',
				orangeStatus: '#F98D50',
				pink: '#f04965',
				pinkStatus: '#C562C3',
				purple: '#C562C3',
				red: '#f33a3d',
				redLight: '#FF9FA3',
				transparent: 'rgba(255, 255, 255, 0)',
				white: '#ffffff',
				yellow: '#fdc436',
				yellowStatus: '#F7A90D',
			},
			fontFamily: {
				// primary: 'Poppins',
				// 'primary-semi-bold': 'Poppins-SemiBold',
				// 'primary-bold': 'Poppins-Bold',
				// secondary: 'SourceSansPro',
				// 'secondary-semi-bold': 'SourceSansPro-SemiBold',
				// 'secondary-bold': 'SourceSansPro-Bold',
			},
			lineHeight: {
				'140': '1.4',
			},
			spacing: {},
		},
	},
};
