# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build"
  desc "Build without code sign. Just to see if the build is working"
  lane :build do |options|
    build_app(
      workspace: "./hubmeeReactNativeMobileApp.xcworkspace",
      scheme: "hubmeeReactNativeMobileApp",
      skip_package_ipa: true,
      skip_archive: true,
      skip_codesigning: true,
      xcargs: "ONLY_ACTIVE_ARCH=YES", # since for this demo we skip_codesigning, the build will be done for a simulator, and since XCode 12, this means arm64, thus build failing. Semaphore is running on x86 chips.
      silent: true, # less logs
      clean: true # clean before build making sure no caching issues
    )
  end
end
